### ISSUE TITLE
qtbase-dev requires GLES headers but does not pull them

### ISSUE THREAD

**Issue by ydirson** [meta-qt5/meta-qt5#102]
When attempting to build a Qt5 app on rk3399 target (with the workaround described in #101 to avoid unaccelerated gles3), build fails with:

```
/usr/include/qt5/QtGui/qopengl.h:110:26: fatal error: GLES2/gl2.h: No such file or directory
 #   include <GLES2/gl2.h>
                          ^
compilation terminated.
```

Dependency on the package providing the relevant headers seem to be missing, libgles2-dev in this particular case, although I guess it should be libgles3-dev or libgl-dev on other platforms.

**Comment by ydirson** [comment]
So what should they be doing to get that dep properly set ?

**Comment by otavio** [comment]
> So what should they be doing to get that dep properly set ?

It depends. On i.MX we made the GPU libraries to depends on `mesa` and we adjusted it to provide just the needed bits.

**Comment by ydirson** [comment]
That does not remove that qtbase-dev requires  header from libgles2-dev, how is that specific dependency supposed to end up in the control file for qtbase-dev to get it pulled ?

I can't see a RDEPENDS append in all meta-qt5 that would be able to fetch that information from the platform definitions.

**Comment by otavio** [comment]
In fact it does. The qtbase-dev will depend on all development packages of dependencies of qtbase. So MALI's -dev packages must add this dependency.

**Comment by ydirson** [comment]
Ah OK, so it all stems from the fact they don't ship mali headers, but just rely on the mesa ones, right ?

**Comment by otavio** [comment]
Yes. It must be dealt by them.
