### ISSUE TITLE
python-pyqt5 error in rocko branch

### ISSUE THREAD

**Issue by vsivanagulu** [meta-qt5/meta-qt5#107]
i am using rocko branch and compiling python-pyqt5. its getting below error.
` failed to create a makefile from PyQt5.pro.
| .8.2-r0/PyQt5_gpl-5.8.2/QtNetwork/QtNetwork.pro
| Reading /home/yocto/build/tmp/work/cortexa9hf-neonlinux-gnueabi/python-pyqt5/5.8.2-r0/PyQt5_gpl-5.8.2/QtWidgets/QtWidgets.pro
| Project ERROR: Unknown module(s) in QT: widgets
`
why i am getting this issue. is there any dependencies issue. i am fresher to work on qt5.

**Comment by shr-project** [comment]
Hi, read README file about the PACKAGECONFIG options in qtbase.
