### ISSUE TITLE
Qt 5.12 update

### ISSUE THREAD

**Issue by bachp** [meta-qt5/meta-qt5#136]
[Qt 5.12 is the new LTS](http://blog.qt.io/blog/2018/12/06/qt-5-12-lts-released/) release. The goal of this issue is to track the progress of upgrading meta-qt5 to Qt 5.12.

**Comment by desert** [comment]
Is it possible it could just need to switch commit SHA hashes and give it a go? If so, I can test it if someone can point me to those sha's.

**Comment by desert** [comment]
Which new module? If so, maybe we can build everything and give it a go, Qt modules are independent by nature, unless there's something im missing.

**Comment by migronof** [comment]
latest 5.12 is quite broken presently. There are exclusive commits now in both 5.12 & 5.12.1 branches in varying amounts depending on module. I'll try to compose an 'upgrade to 5.12.0' commit to master now that I got 5.11.3 done,

**Comment by shr-project** [comment]
https://github.com/meta-qt5/meta-qt5/pull/143
