### ISSUE TITLE
Thud branch build is failing "protocol_handler_registry.cc:23:10: fatal error: chrome/grit/generated_resources.h"

### ISSUE THREAD

**Issue by vishwanathchandapur** [meta-qt5/meta-qt5#148]
I tried build thud branch to get latest chrome but failing with fallowing for imx6.

error.yocto/build/tmp/work/cortexa9t2hf-neon-phytec-linux-gnueabi/qtwebengine/5.11.3+gitAUTOINC+18412af977_2095a35f30-r0/recipe-sysroot-native/usr/bin/arm-phytec-linux-gnueabi/arm-phytec-linux-gnueabi-g++ -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong -D_FORTIFY_SOURCE=2 --sysroot=/home/ubuntu/workspace/Vortex/vortex_bsp_test/yocto/build/tmp/work/cortexa9t2hf-neon-phytec-linux-gnueabi/qtwebengine/5.11.3+gitAUTOINC+18412af977_2095a35f30-r0/recipe-sysroot -MMD -MF obj/qtwebengine_sources/protocol_handler_registry.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DTOOLKIT_QT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../../../git/src/3rdparty/chromium/skia/config -I../../../../git/src/3rdparty/chromium/third_party/boringssl/src/include -I../../../../git/src/3rdparty/chromium/third_party/skia/include/core -Igen -I../../../../git/src/3rdparty/chromium -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -pthread -march=armv7-a -mfloat-abi=hard -mtune=generic-armv7-a -mfpu=neon -mthumb -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wno-psabi -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -gdwarf-3 -g1 -fvisibility=hidden -std=gnu++14 -fno-delete-null-pointer-checks -Wno-narrowing -fno-exceptions -fno-rtti --sysroot=../../../../recipe-sysroot -fvisibility-inlines-hidden -c ../../../../git/src/3rdparty/chromium/chrome/browser/custom_handlers/protocol_handler_registry.cc -o obj/qtwebengine_sources/protocol_handler_registry.o
| ../../../../git/src/3rdparty/chromium/chrome/browser/custom_handlers/protocol_handler_registry.cc:23:10: fatal error: chrome/grit/generated_resources.h: No such file or directory

**Comment by shr-project** [comment]
It looks like missing dependency from protocol_handler_registry.cc, because generated_resources.h are generated a lot later in build where I've reproduced this, the include was removed completely in this commit:

commit 38a9a29f4f9436cace7f0e7abf9c586057df8a4e
Author: Allan Sandfeld Jensen <allan.jensen@qt.io>
Date:   Wed Feb 13 16:23:34 2019 +0100

    BASELINE: Update Chromium to 73.0.3683.37
