### ISSUE TITLE
qtwayland generated header files do not get installed

### ISSUE THREAD

**Issue by SJLC** [meta-qt5/meta-qt5#153]
Qt 5.11.3 and 5.12 versions, current thud and master branches respectively, both suffer from a regression in wayland header file handling -- files generated by wayland scanner during the qtwayland build get skipped in the install. This breaks other projects trying to build against qtwayland

https://bugreports.qt.io/browse/QTBUG-71340 

There was a change in handling of the wayland header files between Qt 5.11.1 (last release where it worked) and later versions: there used to be custom install rules for those headers in mkspecs/features/wayland-scanner.prf, but they got removed in qtbase commit a7730793becc. The claim in that commit was that 
> Generated headers can now be installed using inject_headers and private_headers instead.
however this  theory about using inject_headers and private_headers mechanism to install those generated headers wasn't quite working out in practice -- the install and uninstall rules did not end up in the corresponding Makefiles when building the qtwayland recipe.

It turns out that normally qmake expects that header files to be installed will already exist at the time when Makefiles are being generated. Clearly this isn't true for headers created by wayland scanner.

I am currently testing a workaround that is likely not upstreamable: adding "no_check_exist" to private_headers.CONFIG in mkspecs/featuers/qt_installs.prf (since that is the qmake target where the missing qtwayland headers end up being listed).

Are you interested in a pull request for this patch, if it fixes the qtwayland install and doesn't break the other module builds?

**Comment by shr-project** [comment]
I believe this was resolved.
