### ISSUE TITLE
qtwebkit compilation error

### ISSUE THREAD

**Issue by zangrc-fnst** [meta-qt5/meta-qt5#309]
Hi,
The following error is thrown when compiling qtwebkit:
|Source/WebKit/WebKitWidgets_autogen/J52LRV53MS/moc_DefaultFullScreenVideoHandler.cpp:121: error: undefined reference to 'QWebFullScreenVideoHandler::qt_metacall(QMetaObject::Call, int, void**)'
|Source/WebKit/WebKitWidgets_autogen/J52LRV53MS/moc_DefaultFullScreenVideoHandler.cpp:116: error: undefined reference to 'QWebFullScreenVideoHandler::qt_metacast(char const*)'
|Source/WebKit/CMakeFiles/WebKitWidgets.dir/WebKitWidgets_autogen/mocs_compilation.cpp.o:mocs_compilation.cpp:WebKit::DefaultFullScreenVideoHandler::staticMetaObject: error: undefined reference to 'QWebFullScreenVideoHandler::staticMetaObject'
| /usr/src/debug/qtwebkit/5.14.99+5.15-beta3+gitAUTOINC+ab1bd15209-r0/git/Source/WebKit/qt/Api/qwebfullscreenvideohandler.h:38: error: undefined reference to 'vtable for QWebFullScreenVideoHandler'

**Comment by shr-project** [comment]
see https://github.com/meta-qt5/meta-qt5/pull/307
