### ISSUE TITLE
qtdeclarative install (with examples enabled) fails when doing a clean build in new build directory

### ISSUE THREAD

**Issue by NeenaReddy** [meta-qt5/meta-qt5#318]
qtdeclarative install is failing when built in a clean directory for the first time. Rebuilding it works without even cleaning the package. 
I enabled examples in my qtdeclarative recipe.
PACKAGECONFIG_append = " examples"
Is some dependency missing? 
[qtdeclative_Error.txt](https://github.com/meta-qt5/meta-qt5/files/4612464/qtdeclative_Error.txt)

**Comment by shr-project** [comment]
Fixed in 5.15 with https://codereview.qt-project.org/c/qt/qtdeclarative/+/302578
