### ISSUE TITLE
Add meta-qt5 to core-image-minimal-initramfs

### ISSUE THREAD

**Issue by yong-ruilin** [meta-qt5/meta-qt5#410]
There is no problem in compiling core-image-minimal-initramfs and qtbase separately。
The compilation method is as follows:bitbake core-image-minimal-initramfs   \   bitbake qtbase

I added meta-qt5 to core-image-minimal-initramfs. The way is as follows:
core-image-minimal-initramfs.bb add :
PACKAGE_INSTALL += "qtbase"

Report the following error：
ubuntu@ubuntu18:~/yocto/poky/build$ bitbake core-image-minimal-initramfs
Loading cache: 100% |########################################################################################################################################################################| Time: 0:00:00
Loaded 3801 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies
 
Build Configuration:
BB_VERSION           = "1.49.2"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "mips64el-loongson-linux"
MACHINE              = "loongson2k"
DISTRO               = "loongson"
DISTRO_VERSION       = "2.5.3"
TUNE_FEATURES        = "n64 fpu-hard gs464e"
TARGET_FPU           = ""
meta                 
meta-poky            
meta-yocto-bsp       
meta-loongson        = "master:e1839b58ebe05242a52fe050aa9a08140136aa0a"
meta-qt5             = "master:a00af3eae082b772469d9dd21b2371dd4d237684"
meta-oe              
meta-python          
meta-networking      
meta-initramfs       
meta-multimedia      
meta-filesystems     = "master:555b90779f6d86f7df05604f474323d9aef96886"
 
Initialising tasks: 100% |###################################################################################################################################################################| Time: 0:00:01
Sstate summary: Wanted 11 Local 9 Network 0 Missed 2 Current 997 (81% match, 99% complete)
NOTE: Executing Tasks
ERROR: core-image-minimal-initramfs-1.0-r0 do_rootfs: The postinstall intercept hook 'update_gio_module_cache' failed, details in /home/ubuntu/yocto/poky/build/tmp/work/loongson2k-loongson-linux/core-image-minimal-initramfs/1.0-r0/temp/log.do_rootfs
ERROR: Logfile of failure stored in: /home/ubuntu/yocto/poky/build/tmp/work/loongson2k-loongson-linux/core-image-minimal-initramfs/1.0-r0/temp/log.do_rootfs.16361
ERROR: Task (/home/ubuntu/yocto/poky/meta/recipes-core/images/core-image-minimal-initramfs.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3093 tasks of which 3092 didn't need to be rerun and 1 failed.
 
Summary: 1 task failed:
  /home/ubuntu/yocto/poky/meta/recipes-core/images/core-image-minimal-initramfs.bb:do_rootfs
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
 
log.do_rootfs file：
NOTE: Exit code 132. Output:
+ [ True = False -a qemuwrapper-cross != nativesdk-qemuwrapper-cross ]
+ qemu-mips64el -r 3.2.0 -E LD_LIBRARY_PATH=/home/ubuntu/yocto/poky/build/tmp/work/loongson2k-loongson-linux/core-image-minimal-initramfs/1.0-r0/rootfs/usr/lib:/home/ubuntu/yocto/poky/build/tmp/work/loongson2k-loongson-linux/core-image-minimal-initramfs/1.0-r0/rootfs/lib -L /home/ubuntu/yocto/poky/build/tmp/work/loongson2k-loongson-linux/core-image-minimal-initramfs/1.0-r0/rootfs /home/ubuntu/yocto/poky/build/tmp/work/loongson2k-loongson-linux/core-image-minimal-initramfs/1.0-r0/rootfs/usr/libexec/gio-querymodules /home/ubuntu/yocto/poky/build/tmp/work/loongson2k-loongson-linux/core-image-minimal-initramfs/1.0-r0/rootfs/usr/lib/gio/modules/
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
Illegal instruction (core dumped)

NOTE: ydebug 6
ERROR: The postinstall intercept hook 'update_gio_module_cache' failed, details in /home/ubuntu/yocto/poky/build/tmp/work/loongson2k-loongson-linux/core-image-minimal-initramfs/1.0-r0/temp/log.do_rootfs
DEBUG: Python function do_rootfs finished

Can anyone help me solve the problem，thanks.

**Comment by shr-project** [comment]
This doesn't look related to qt5, meta-qt5 doesn't change gio-querymodules to cause Illegal instruction there, try minimal image with some other package which includes gio_module_cache postinst and you should be able to reproduce it without qtbase as well.

**Comment by shr-project** [comment]
Try to narrow down what introduced this Illegal instruction in gio-querymodules in first place. If it worked before, then it might be the gcc-11 upgrade, I've seen it in fc-cache, see https://lists.yoctoproject.org/g/meta-virtualization/message/6492

**Comment by yong-ruilin** [comment]
I added the following configuration to temporarily solve the problem
MACHINE_FEATURES_BACKFILL_CONSIDERED += "qemu-usermode"
