### ISSUE TITLE
tqtc-qtbase download error

### ISSUE THREAD

**Issue by blithe2015** [meta-qt5/meta-qt5#470]
![image](https://user-images.githubusercontent.com/48937574/169733524-259fee1b-6dbd-4de8-9c95-d47ee36c920a.png)
git clone git://codereview.qt-project.org/qt/tqtc-qtbase.git
Cloning into 'tqtc-qtbase'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by shr-project** [comment]
This is wrong place, this project isn't maintained by tqtc, you need to report this to them.
