### ISSUE TITLE
Commit 88c8564eb58d28768165fde0d6ab9e88b42ddc8f deleted python3-pyqt5

### ISSUE THREAD

**Issue by minecraft2048** [meta-qt5/meta-qt5#503]
Is this intentional? The commit message only mentions qtwebkit and ruby, nothing to do with python3-pyqt5

**Comment by shr-project** [comment]
Probably not intentional, but it depends on sip3 which was removed in:
https://git.openembedded.org/meta-openembedded/commit/?id=4dc1c6e16b31d30aca05c52fa0209c74eedd6842

so someone needs to resolve these issues before it can be built again.
