### ISSUE TITLE
Update to Qt 5.15.9 LGPL (opensource)

### ISSUE THREAD

**Issue by bernhardHartleb** [meta-qt5/meta-qt5#516]
Release announcement here:
[https://lists.qt-project.org/pipermail/announce/2023-April/000406.html](https://lists.qt-project.org/pipermail/announce/2023-April/000406.html)

I am willing to make a PR if desired.
Thank you.

**Comment by bernhardHartleb** [comment]
For reference:
[https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.8/release-note.md](https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.8/release-note.md)
[https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.9/release-note.md](https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.9/release-note.md)

**Comment by shr-project** [comment]
> I am willing to make a PR if desired.

Please go ahead.

**Comment by chakuzo** [comment]
I am also interested, also support if needed.

**Comment by fmntf** [comment]
This issue should be closed since 5.15.9 is already on master branch.
