### ISSUE TITLE
SRCREV_FORMAT with underscores generates Debian packages with invalid versions

### ISSUE THREAD

**Issue by czw** [meta-qt5/meta-qt5#518]
Some of the recipes, for example `qtlocation`, contains version numbers with underscores in them. The packages will build just fine, but adding the resulting `qtlocation_5.15.3+git0+9909253b0f_d3101bbc22-r0_amd64.deb` file to a Debian package repository with `reprepro` yields the following error:

    Character '_' not allowed in version: '5.15.3+git0+9909253b0f_d3101bbc22-r0'

I am willing to make a PR if desired. All I need to know is if it's OK to replace the underscore with a plus sign.

**Comment by shr-project** [comment]
Every SRCREV_FORMAT I've found is using underscore as separator, so this would be better to discuss on oe-core ML first as it doesn't affect just qt5 recipes.

**Comment by czw** [comment]
Correct, this is probably best done in the deb archive creation side. Closing.
