### ISSUE TITLE
Update to Qt 5.15.10 LGPL (opensource)

### ISSUE THREAD

**Issue by chakuzo** [meta-qt5/meta-qt5#530]
Release notes: https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.10/release-note.md

I know there is the meta-qt6 branch. But I am still bound to Qt5. I would also do the PR.

**Comment by paletteguy** [comment]
Want it too :)

**Comment by fmntf** [comment]
This issue can be closed after https://github.com/meta-qt5/meta-qt5/pull/550 gets merged.
