### ISSUE TITLE
 Is there a plan to release the nanbiled branch?

### ISSUE THREAD

**Issue by sangmo-kang** [meta-qt5/meta-qt5#562]
Dear Maintainers.
After https://github.com/meta-qt5/meta-qt5/commit/6e244970dcdb631613af80f37e00957de417449d commit, it appears that there is no branch with nanbield in LAYERSERIES_COMPAT_qt5-layer.
I would like to inquire whether the nanbiled branch is scheduled to be released.

Many thanks.

**Comment by shr-project** [comment]
See https://github.com/meta-qt5/meta-qt5/pull/561

**Comment by sangmo-kang** [comment]
> See #561

Dear @shr-project.

Thank you for the release of the nanbield branch.
